version: "3"

services:
  julis-service-register-app:
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    container_name: julis-service-register-app
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes: 
      - ../config.dev.yml:/config.yml
    environment:
      JSR_CONFIG: "/config.yml"
      JSR_DATABASE_HOST: "postgres"
      JSR_LLDAP_HOST: "lldap:17170"

  postgres:
    image: postgres:latest
    container_name: julis-service-register-app-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  lldap:
    image: nitnelave/lldap:latest
    container_name: lldap
    ports:
      - 17170:17170
    volumes:
      - ./devdata/lldap:/data
    environment:
      LLDAP_JWT_SECRET: "lldap"
      LLDAP_LDAP_USER_PASS: "password1"
      LLDAP_LDAP_BASE_DN: "dc=example,dc=com"
