api:
  bind: 0.0.0.0:8080

database:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres

lldap:
  host: localhost:17170
  username: admin
  password: password1