version: "3"

services:
  julis-service-register-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: julis-service-register-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      JULIS_REGISTER_APP_CONFIG_PATH: "/config.yml"

  postgres:
    image: postgres:latest
    container_name: julis-service-register-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
